config/routes.rb
Rails.application.routes.draw do
  root to: 'onboarding#index'
  mount ShopifyApp::Engine, at: '/'
  mount Resque::Server, at: '/resque'

  get '/welcome' => 'onboarding#index', as: :welcome
  get '/welcome/scan' => 'onboarding#scan', as: :welcome_scan
  get '/welcome/status' => 'onboarding#status', as: :welcome_status
  get '/welcome/result' => 'onboarding#result', as: :welcome_result

  get '/customer/archive/:id' => 'customers#archive', as: :customer_archive
  get '/customer/unarchive/:id' => 'customers#unarchive', as: :customer_unarchive

  resources :customers, only: [:index, :show, :new, :create, :destroy]
  resource :shop, only: [:edit, :update]
  get '/shop/plan' => 'shops#plan', as: :plan
  get '/shop/plans/update_plan_step_2' => 'shops#update_plan_step_2', as: :update_plan_step_2
  patch '/shop/plans/update_plan_step_1' => 'shops#update_plan_step_1', as: :update_plan_step_1
  post '/customer/bulk_scan' => 'customers#bulk_scan', as: :bulk_scan

  scope '/hooks', controller: :hooks do
    post :new_customer_callback
    post :app_uninstalled_callback
  end

end

app/models/shop.rb
require './lib/modules/plan'

class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include Plan
  include Rails.application.routes.url_helpers
  has_many :customers, inverse_of: :shop, dependent: :destroy

  ## Shop model is where we store sessions
  def self.store(session)
    shop = Shop.where(shopify_domain: session.url).first

    if shop.present?
      shop.shopify_token = session.token
      shop.save!
    else
      shop = Shop.create(shopify_domain: session.url, shopify_token: session.token)
    end

    shop.install unless shop.installed
    shop.id
  end

  def self.retrieve(id)
    return unless shop = Shop.where(id: id).first
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  end

  def self.mrr
    @mrr = 0
    Plan.names.each do |plan|
      mrr = Shop.where(installed: true).where(plan: plan).count * Plan.cost(plan)
      @mrr += mrr
    end
    @mrr
  end

  def install
    shopify_session
    set_email
    send_install_notification
    init_webhooks
    self.installed = true
    save
  end


  # we must instantiate a shopify session when we want to make a call to the Shopify API
  def shopify_session
    shop_session = ShopifyAPI::Session.new(shopify_domain, shopify_token)
    ShopifyAPI::Base.activate_session(shop_session)
  end

  def free_influencer_scans_remaining
    teaser_celebrity ? 0 : 1
  end

  def basic_scans_allowed
    Plan.basic_scans(plan)
  end

  def basic_scans_performed(days)
    customers.where('created_at > ?', days.days.ago).where(freebie_scan: false).count
  end

  def basic_scans_remaining
    if plan == 'free'
      sum = basic_scans_allowed - basic_scans_performed(3650)
    else
      sum = basic_scans_allowed - basic_scans_performed(30)
    end

    sum < 0 ? 0 : sum
  end

  def social_scans_allowed
    Plan.social_scans(plan)
  end

  def social_scans_performed(days)
    customers.where('created_at > ?', days.days.ago).where(scanned_on_social: true).where(freebie_scan: false).count
  end

  def social_scans_remaining
    sum = social_scans_allowed - social_scans_performed(30)
    sum = 0 if plan == 'free'
    sum < 0 ? 0 : sum
  end

  def unscanned_customer_count
    num = ShopifyAPI::Customer.count - customers.count
    num = 0 if num < 0
    num
  end

  def teaser_scans_running?
    !Plan.social_scans_enabled?(plan) && !teaser_celebrity
  end


  #onboard scan runs when store owner first installs the app. It scans up to 750 customers to find a customer
  # with at least 1000 followers on a social channel. Average is 120 scans to hit.
  def onboard_scan
    return if onboarded

    customers_to_scan = all_customers(750)

    @celebrity = nil
    @celebrities_count = 0
    @count = 0

    self.email_notifications = false

    while @celebrities_count == 0 && @count < 750 || @count >= customers_to_scan.count
      shopify_customer = customers_to_scan[@count]
      return unless shopify_customer
      customer = customers.new(
        first_name: shopify_customer.first_name,
        last_name: shopify_customer.last_name,
        email: shopify_customer.email,
        shopify_id: shopify_customer.id,
        freebie_scan: true
      )

      customer.teaser_scan
      @count += 1

      next unless customer.teaser_celebrity?
      @celebrity = customer
      @celebrity.status = 'celebrity'
      @celebrity.save
      @celebrities_count += 1

    end

    self.email_notifications = true
    save

    @celebrity
  end

  # store owner has the option to re-scan their previously scanned customers
  def bulk_scan(num, include_previously_scanned)
    shop_session = Shop.retrieve(self.id)
    ShopifyAPI::Base.activate_session(shop_session)

    customers_to_scan = shopify_customers(num, include_previously_scanned)
    scanned_count = customers_to_scan.count

    if scanned_count > 0

      @celebrities_count = 0

      emails_on = email_notifications

      self.email_notifications = false if emails_on

      customers_to_scan.each do |shopify_customer|

        @cleaned_email = shopify_customer.email.sanitize_email if shopify_customer.email

        if @cleaned_email
          @existing_customer = Customer.where(email: @cleaned_email).first 
          @existing_shop_customer = self.customers.where(email: @cleaned_email).first
        end

        if @existing_shop_customer
          customer = @existing_shop_customer
          customer.archived = false
        elsif @existing_customer
          customer = @existing_customer.dup
          customer.shop_id = self.id
          customer.archived = false
        else
          customer = self.customers.new(
          first_name: shopify_customer.first_name,
          last_name: shopify_customer.last_name,
          email: shopify_customer.email,
          shopify_id: shopify_customer.id
        )
          customer.scan
        end

        customer.save

        @celebrities_count += 1 if customer.celebrity?
      end

      self.email_notifications = true if emails_on

    end

    [scanned_count, @celebrities_count]
  end


  # step 1 of the shopify recurring charge process. charge must be confirmed by user and then activated by app
  def confirm_charge(shopify_plan)
    if shopify_plan != plan

      if shopify_plan == 'free'

        if charge = charge_id
          recurring = ShopifyAPI::RecurringApplicationCharge.find(charge)
          recurring.destroy
          self.charge_id = nil
        end

        old_plan = plan
        self.plan = 'free'
        save
        NotificationMailer.plan_change(self, old_plan).deliver_now
        customers_url(host: Figaro.env.root_uri)

      else
        price = Plan.cost(shopify_plan)
        name = shopify_plan + ' Alpha Club Plan'
        return_url = update_plan_step_2_url(host: Figaro.env.root_uri)
        response = ShopifyAPI::RecurringApplicationCharge.create(name: name,
                                                                 price: price,
                                                                 return_url: return_url,
                                                                 test: !Rails.env.production?)
        response.confirmation_url
      end

    else
      customers_url(host: Figaro.env.root_uri)
    end
  end


  # step 2 of shopify recurring charge process
  def activate_charge(charge)
    if charge.status == 'accepted'
      plan = charge.name.split.first
      charge.activate
      self.plan = plan
      self.charge_id = charge.id
      plan
    end
  end


  # returns X customers from the shopify API. 
  # option to only get those customers who have not yet been scanned
  def shopify_customers(num, include_previously_scanned)
    if include_previously_scanned
      all_customers(num)
    else
      unscanned_customers(num)
    end
  end

  # returns X most recent customers back from Shopify API
  # Verbose code is because Shopify only allows you to get a max of 250 customers at a time
  def all_customers(number_of_customers_to_return)
    pages = 1
    num = number_of_customers_to_return

    if number_of_customers_to_return > 250
      num = 250
      total_customers = ShopifyAPI::Customer.count
      pages = (total_customers / 250.to_f).ceil
    end

    @count = 0
    @customers = []

    until @customers.count == number_of_customers_to_return do
      @count += 1
      result = ShopifyAPI::Customer.find(:all, params: { limit: num, page: @count })
      @customers += result.to_a
      break if @count == pages    
    end

    @customers.first(number_of_customers_to_return)
  end

  # returns X most recent customers (who have not been scanned by Alpha Club) back from Shopify API
  def unscanned_customers(num)
    num = basic_scans_remaining if num > basic_scans_remaining

    @total_customers = ShopifyAPI::Customer.count
    pages = (@total_customers / 250.to_f).ceil

    @page_count = 0
    @filtered_customers = []

    while @filtered_customers.count < num && @page_count < pages

      @page_count += 1
      @customers_on_page = ShopifyAPI::Customer.find(:all, params: { limit: 250, page: @page_count })

      @counter = 0

      while @filtered_customers.count < num && @counter < @customers_on_page.count
        customer = @customers_on_page[@counter]

        if customers.where(shopify_id: customer.id).first.blank?
          @filtered_customers << customer
        end

        @counter += 1
      end

    end

    @filtered_customers
  end

  # runs on first install to setup webhooks
  def init_webhooks
    unless Rails.env.test?
      new_customer_callback_url = Figaro.env.root_uri + '/hooks/new_customer_callback'
      uninstall_callback_url = Figaro.env.root_uri + '/hooks/app_uninstalled_callback'

      new_customer_webhook = ShopifyAPI::Webhook.new(topic: 'customers/create', format: 'json', address: new_customer_callback_url)
      uninstall_webhook = ShopifyAPI::Webhook.new(topic: 'app/uninstalled', format: 'json', address: uninstall_callback_url)

      new_customer_webhook.save
      uninstall_webhook.save
    end
  end
  
  # returns an array of customers who are marked as celebrities
  def celebrities
    customers.where(status: 'celebrity').where(archived: false).order(created_at: :desc)
  end

  # runs when shop is first installed, gets store owners email from the shopify API
  def set_email
    unless Rails.env.test?
      update_attributes(email: ShopifyAPI::Shop.current.email)
    end
  end


  def twitter_follower_threshold=(followers)
    write_attribute(:twitter_follower_threshold, "#{followers}".gsub(/\D/, ''))
  end

  # sent to store owner whenever a new celebrity is found
  def send_celebrity_notification(celebrity)
    if email_notifications
      NotificationMailer.celebrity_notification(celebrity).deliver_now
   end
  end

  private

  # sent to app owner whenever new shop installs
  def send_install_notification
    NotificationMailer.install_notification(self).deliver_now
  end
end

app/controllers/shops_controller.rb
class ShopsController < AuthenticatedController
  require './lib/modules/plan'
  include Plan

  def edit
    @shop = current_shop
    @basic_scans_remaining = current_shop.basic_scans_remaining
    @social_scans_remaining = current_shop.social_scans_remaining
    @free_influencer_scans_remaining = current_shop.free_influencer_scans_remaining
  end

  def plan
    @shop = current_shop
    @basic_scans_remaining = current_shop.basic_scans_remaining
    @social_scans_remaining = current_shop.social_scans_remaining
    @free_influencer_scans_remaining = current_shop.free_influencer_scans_remaining
  end

  def update
    @shop = current_shop

    if @shop.update_attributes(shop_params)
      Resque.enqueue(CelebrityUpdater, @shop.id)
      flash[:success] = 'Settings Successfully Saved'
      redirect_to customers_url
    else
      render :edit
    end
  end

  def update_plan_step_1
    @plan = shop_params[:plan]
    redirect_url = current_shop.confirm_charge(@plan)
    if redirect_url == customers_url
      flash[:success] = "Alpha Club Plan Updated! You are now on the #{@plan} plan. Yay!"
      redirect_to customers_url
    else
      gon.authorization_url = redirect_url
      render :redirect_to_shopify_auth
    end
  end

  def update_plan_step_2
    charge = ShopifyAPI::RecurringApplicationCharge.first
    old_plan = current_shop.plan
    new_plan = current_shop.activate_charge(charge)
    current_shop.save

    if new_plan
      NotificationMailer.plan_change(current_shop, old_plan).deliver_now
      flash[:notice] = "You are now on the #{new_plan.capitalize} Alpha Club Plan. Yay!"
    else
      flash[:alert] = 'Charge not processed properly, please try again'
       end

    redirect_to customers_url
  end

  protected

  def shop_params
    params.require(:shop).permit(
      :email_notifications, :wikipedia_notification, :imdb_notification, :twitter_follower_threshold, :instagram_follower_threshold, :klout_score_threshold, :youtube_subscriber_threshold, :plan)
  end
end

app/views/shops/_celebrity_odds.erb
<div class="panel panel-info col-lg-8 col-lg-offset-2 text-center">
	 <div class="panel-body">
	 	<h2>What are the odds one of your customers will be a celebrity?</h2>
	 	<p>This number will vary from shop to shop, but here are some approximate stats based on our current users.</p>
	 	<table class="table table-bordered">
         	<thead>
  				<tr><th>Celebrity Type</th><th>Odds</th><th>Accuracy</th></tr>
  			</thead>
  			<tbody>
  				<tr><td>IMDB Page</td><td>1 in 8 customers</td><td>Name Match Only (less accurate)</td></tr>
  				<tr><td>Wikipedia Page</td><td>1 in 14 customers</td><td>Name Match Only (less accurate)</td></tr>
  				<tr><td>1,000 Followers (twitter, instagram, or youtube)</td><td>1 in 120 customers</td><td>Email Match (very accurate)</td></tr>
  				<tr><td>5,000 Followers (twitter, instagram, or youtube)</td><td>1 in 360 customers</td><td>Email Match (very accurate)</td></tr>
  				<tr><td>50,000 Followers (twitter, instagram, or youtube)</td><td>1 in 1400 customers</td><td>Email Match (very accurate)</td></tr>
  				<tr><td>100,000 Followers (twitter, instagram, or youtube)</td><td>1 in 2400 customers</td><td>Email Match (very accurate)</td></tr>
  				<tr><td>250,000 Followers (twitter, instagram, or youtube)</td><td>1 in 3500 customers</td><td>Email Match (very accurate)</td></tr>
  			</tbody>
     	</table>

	 </div>
</div>

app/views/shops/_scans_remaining.html.erb
<div style="display: none;">
  <% if @shop.plan == "free" %>
  	<%= @basic_scans_remaining %> Wikipedia/IMDB scans remaining (follower counts disabled)</p>
  <% elsif @shop.plan == "junior" %>
  	<p>Unlimited Wikipedia/IMDB scans (follower counts disabled)</p>
  <% else %>
  	<p>Unlimited Wikipedia/IMDB scans and <span id="scans-remaining"><%= @social_scans_remaining %></span> social scans remaining this month</p>
  <% end %>
</div>

app/views/shops/_social_settings.html.erb
<% unless @shop.plan == "free" || @shop.plan == "junior" %>
	<div>
		<p>Customers who have over <%= f.number_field :twitter_follower_threshold, :style=>"width:75px;" %> Twitter followers should be considered celebrities.</p>
	</div>

	<div>
		<p>Customers who have over <%= f.number_field :youtube_subscriber_threshold, :style=>"width:75px;" %> Youtube subscribers should be considered celebrities.</p>
	</div>

	<div>
		<p>Customers who have over <%= f.number_field :instagram_follower_threshold, :style=>"width:75px;" %> Instagram followers should be considered celebrities.</p>
	</div>

	<div>
		<p>Customers who have a Klout score over <%= f.number_field :klout_score_threshold, :style=>"width:75px;", :max=> 100 %> should be considered celebrities.</p>
	</div>
<% else %>
 	<div class="alert alert-info">
 		<p>Follower count scanning is disabled on some plans, but we'll notify you of your first influencer for free (over 1000 followers).</p>
 	</div>
	<p> Or you can <%= link_to 'upgrade', plan_path %> your plan to start seeing followers right away</p>
 	<div class="disabled-social-data">
	 	<div>
			<p>Customers who have over <%= f.number_field :twitter_follower_threshold, :style=>"width:75px;" %> Twitter followers should be considered celebrities. <%= f.check_box :twitter_follower_threshold, :data => { :toggle => 'toggle', :onstyle=>"info", :size=>"mini" }, :disabled=> true %></p>
		</div>

		<div>
			<p>Customers who have over <%= f.number_field :youtube_subscriber_threshold, :style=>"width:75px;" %> Youtube subscribers should be considered celebrities. <%= f.check_box :youtube_subscriber_threshold, :data => { :toggle => 'toggle', :onstyle=>"info", :size=>"mini" }, :disabled=> true %></p>
		</div>

		<div>
			<p>Customers who have over <%= f.number_field :instagram_follower_threshold, :style=>"width:75px;" %> Instagram followers should be considered celebrities. <%= f.check_box :instagram_follower_threshold, :data => { :toggle => 'toggle', :onstyle=>"info", :size=>"mini" }, :disabled=> true %></p>
		</div>

		<div>
			<p>Customers who have a Klout score over <%= f.number_field :klout_score_threshold, :style=>"width:75px;", :max=> 100 %> should be considered celebrities. <%= f.check_box :klout_score_threshold, :data => { :toggle => 'toggle', :onstyle=>"info", :size=>"mini" }, :disabled=> true %></p>
		</div>
	</div>
<% end %>

app/views/shops/authorize_payment.html.erb
<script>
  window.top.location.href = gon.authorization_url;
</script>

app/views/shops/edit.html.erb
<span id="notice"><%= notice %></span>

<div class="container settings">
<%= render 'customers/header' %>
<div class="col-lg-8 col-lg-offset-2">
  <h1>Settings</h1>
  <%= link_to "< Back to Celebrities & Influencers", customers_path %>
 </div>

<div class="clearfix"></div>
<div class="spacer"></div>

<div class="panel panel-default col-lg-8 col-lg-offset-2 text-center">
	 <div class="panel-body">
		  <%= form_for @shop do |f| %>

		      <h2>Current Plan: <%= @shop.plan.titleize %></h2>
		      <%= link_to 'change plan', plan_path %>
		  
		    
			 <div class="spacer"></div>

			 <p>Email Notifications: <%= f.check_box :email_notifications, :data => { :toggle => 'toggle', :onstyle=>"info", :size=>"mini" } %></p>


			 <p>Customers who have Wikipedia pages should be considered celebrities: <%= f.check_box :wikipedia_notification, :data => { :toggle => 'toggle', :on => "Yes", :off => "No", :onstyle=>"success", :size=>"mini" } %></p>
			 <p>Customers who have IMDB pages should be considered celebrities: <%= f.check_box :imdb_notification, :data => { :toggle => 'toggle', :on => "Yes", :off => "No", :onstyle=>"success", :size=>"mini" } %></p>

			 <%= render 'social_settings', :f => f %>
			  

			<%= f.submit 'Save Settings', :class=>"btn btn-success" %>

		<% end %>
		  </div>

		  
  </div>




<div class="spacer"></div>

<%= render 'celebrity_odds' %>

</div>


<script> 

function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

$('#shop_twitter_follower_threshold').on('change keyup', function(){
	var twitterCount = numberWithCommas($('#shop_twitter_follower_threshold').val())
	$('.twitter-count').text(twitterCount);
}).triggerHandler('keyup');
	
</script>

app/views/shops/plan.html.erb
<span id="notice"><%= notice %></span>

<div class="container settings">
	<%= render 'customers/header' %>
  <div class="col-lg-8 col-lg-offset-2">
  <%= link_to "< Back to Celebrities & Influencers", customers_path %>
 </div>
 <div class="clearfix spacer"></div>
  <a name="plan"></a>
  <div class="panel panel-default col-lg-8 col-lg-offset-2 text-center">
  	<div class="panel-header">
  	 <h1>You are on the <%= @shop.plan.titleize %> Alpha Club Plan</h1>
  	</div>
	 <div class="panel-body">
		  <%= form_for @shop, :url => update_plan_step_1_path do |f| %>


	         <div>
	         	<%= f.radio_button :plan, 'free', :checked => true %> 
	         	<%= label :plan_free, 'Free' %>
	         	<%= f.radio_button :plan, 'basic' %>
	         	<%= label :plan_basic, 'Basic' %>
	         	<%= f.radio_button :plan, 'pro' %>
	         	<%= label :plan_pro, 'Pro' %>
	         	<%= f.radio_button :plan, 'stalker' %>
	         	<%= label :plan_stalker, 'Stalker' %>
	         	<%= f.radio_button :plan, 'god' %>
	         	<%= label :plan_god, 'God Mode' %>
	         </div>

	         <div class="spacer">
	         	<table class="table table-bordered">
		         	<thead>
	      				<tr><th></th><th>Free</th><th>Basic ($29/mo)</th><th>Pro ($59/mo)</th><th>Stalker ($99/mo)</th><th>God Mode ($199/mo)</th></tr>
	      			</thead>
	      			<tbody>
	      				<tr><td>Wikipedia & IMDB Scans</td><td>20</td><td>Unlimited</td><td>Unlimited</td><td>Unlimited</td><td>Unlimited</td></tr>
	      				<tr><td>Follower Social Scans</td><td><i class="glyphicon glyphicon-remove"></i></td><td>200 scans/mo</td><td>1000 scans/mo</td><td>2500 scans/mo</td><td>6000 scans/mo</td></tr>
	      				<tr><td>Bulk Scan Past Customers</td><td><i class="glyphicon glyphicon-remove"></i></td><td><i class="glyphicon glyphicon-remove"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></td></tr>
	      			</tbody>
	         	</table>
	         	<div class="text-center">
	         		<p>Need more than 6000 scans per month? <%= link_to 'Contact us', 'mailto:jackson@pixelburst.co' %></p>
	         	</div>
	         </div>
<!-- 
	         	<tr><td>Wikipedia Scanning</td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td></tr>
	      				<tr><td>IMDB Scanning</td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td></tr>
	      				<tr><td>Twitter Scanning</td><td><i class="glyphicon glyphicon-ok"></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td></tr>
	      				<tr><td>Instagram Scanning</td><td><i class="glyphicon glyphicon-ok"></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td></tr>
	      				<tr><td>Youtube Scanning</td><td><i class="glyphicon glyphicon-ok"></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td></tr>
	      				<tr><td>Klout Scanning</td><td><i class="glyphicon glyphicon-ok"></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td><td><i class="glyphicon glyphicon-ok"></i></td></tr>
 -->
	         

			<%= f.submit 'Update Plan', :class=>"btn btn-info" %>

		<% end %>
		  </div>
  </div>




<div class="spacer"></div>

<%= render 'celebrity_odds' %>

<div class="spacer"></div>



</div>

app/views/shops/redirect_to_shopify_auth.html.erb
<script>
  window.top.location.href = gon.authorization_url;
</script>