config/routes.rb
Rails.application.routes.draw do
  root to: 'onboarding#index'
  mount ShopifyApp::Engine, at: '/'
  mount Resque::Server, at: '/resque'

  get '/welcome' => 'onboarding#index', as: :welcome
  get '/welcome/scan' => 'onboarding#scan', as: :welcome_scan
  get '/welcome/status' => 'onboarding#status', as: :welcome_status
  get '/welcome/result' => 'onboarding#result', as: :welcome_result

  get '/customer/archive/:id' => 'customers#archive', as: :customer_archive
  get '/customer/unarchive/:id' => 'customers#unarchive', as: :customer_unarchive

  resources :customers, only: [:index, :show, :new, :create, :destroy]
  resource :shop, only: [:edit, :update]
  get '/shop/plan' => 'shops#plan', as: :plan
  get '/shop/plans/update_plan_step_2' => 'shops#update_plan_step_2', as: :update_plan_step_2
  patch '/shop/plans/update_plan_step_1' => 'shops#update_plan_step_1', as: :update_plan_step_1
  post '/customer/bulk_scan' => 'customers#bulk_scan', as: :bulk_scan

  scope '/hooks', controller: :hooks do
    post :new_customer_callback
    post :app_uninstalled_callback
  end

end

app/models/customer.rb
require 'open-uri'
require 'json'
require 'pry'

class Customer < ActiveRecord::Base
  belongs_to :shop

  before_validation :sanitize
  before_create :scans_depleted_notification
  validates_presence_of :shop, on: :create

  # performs a scan on the customer to see if there is a 
  # IMDB, Wikipedia match or large social following
  def scan
    sanitize
    data = get_external_data
    return unless data
    get_celebrity_status
    if self.celebrity?
      shop.send_celebrity_notification(self)
      self.status = 'celebrity'
    end
  end

  # teaser scans are a method of converting unpaid users
  # the main difference from the scan method is that fullcontact_data is forced to be called
  # even when shop has no social scans remaining, so that we can show store owners how the app
  # works by providing them with a free influencer notification
  def teaser_scan
    return if shop.onboarded
    data = fullcontact_data
    return unless data

    set_social_data

    if self.teaser_celebrity?
      shop.teaser_celebrity = true
      shop.save
      NotificationMailer.teaser(self).deliver_now
    end
  end

  # gets all data from external APIs, does not get full contact data unless shop 
  # has social scans remaining (upgraded plans)
  def get_external_data
    @wikipedia_data = wikipedia_data
    @imdb_data = imdb_data
    @fullcontact_data = fullcontact_data if shop.social_scans_remaining > 0
    true if @wikipedia_data || @imdb_data || @fullcontact_data
  end


  # sets external data if it exists
  def get_celebrity_status
    set_imdb if @imdb_data
    set_wikipedia if @wikipedia_data
    set_social_data if @fullcontact_data
  end

  # returns true if customer is a celebrity based on the thresholds set by the store owner
  def celebrity?
    imdb_celebrity? ||
      wikipedia_celebrity? ||
      twitter_celebrity? ||
      instagram_celebrity? ||
      youtube_celebrity? ||
      klout_celebrity?
  end

  def shopify_url
    shop.shopify_domain + '/admin/customers/' + shopify_id.to_s
  end

  def full_name
    first_name + ' ' + last_name if first_name.present? && last_name.present?
  end

  def set_social_data
    set_twitter
    set_linkedin
    set_angellist
    set_klout
    set_instagram
    set_youtube
  end

  def fullcontact_data
    @fullcontact ||= Fullcontact.new(self)
    self.scanned_on_social = true
    fullcontact_data ||= @fullcontact.data
  end

  def imdb_celebrity?
    imdb_url && shop.imdb_notification
  end

  def wikipedia_celebrity?
    wikipedia_url && shop.wikipedia_notification
  end

  def youtube_celebrity?
    youtube_subscribers && youtube_subscribers > shop.youtube_subscriber_threshold
  end

  def instagram_celebrity?
    instagram_followers && instagram_followers > shop.instagram_follower_threshold
  end

  def klout_celebrity?
    klout_score && klout_score > shop.klout_score_threshold
  end

  def twitter_celebrity?
    twitter_followers && twitter_followers > shop.twitter_follower_threshold
  end

  def imdb_data
    return unless first_name.present? && last_name.present? && full_name.ascii_only?
    @imdb ||= IMDB.new(self)
    data ||= @imdb.data
  end

  def wikipedia_data
    return unless first_name.present? && last_name.present? && full_name.ascii_only?
    @wikipedia ||= Wikipedia.new(self)
    @wikipedia.data
  end

  def self.search(search, page)
    paginate per_page: 10, page: page,
             conditions: ['name like ?', "%#{search}%"],
             order: 'name'
  end

  def duplicate?
    true if shop.customers.where(shopify_id: shopify_id).first
  end

  # This is what determines a teaser celebrity. Once a teaser celebrity is found, store owner is notified and a flag
  # is switched in the shop so that no more teaser scans are run
  def teaser_celebrity?
    true if twitter_followers && twitter_followers > 1000 || youtube_subscribers && youtube_subscribers > 1000 || instagram_followers && instagram_followers > 1000
  end

  ## analytics data for app owner. We can see how often certain "celebrities" will occur

  def self.percentage_with_imdb_match
    @count ||= Customer.count.to_f
    imdb_count = where('imdb_url IS NOT NULL').count
    (imdb_count).percent_of(@count)
  end

  def self.percentage_with_wikipedia_match
    @count ||= Customer.count
    wikipedia_count = where('wikipedia_url IS NOT NULL').count
    (wikipedia_count).percent_of(@count)
  end

  def self.percentage_with_followers(num_followers)
    customers = where(scanned_on_social: true).where('created_at > ?', 'Sat, 31 Oct 2015').where(freebie_scan: false)

    twitter_followers = customers.where('twitter_followers > ?', num_followers).count
    instagram_followers = customers.where('instagram_followers > ?', num_followers).count
    youtube_subscribers = customers.where('youtube_subscribers > ?', num_followers).count
    followers_count = twitter_followers + instagram_followers + youtube_subscribers
    (followers_count).percent_of(customers.count)
  end

  def self.percentage_with_klout_score(score)
    customers = where(scanned_on_social: true).where('created_at > ?', 'Sat, 31 Oct 2015').where(freebie_scan: false)
    klout_count = customers.where('klout_score > ?', score).count
    (klout_count).percent_of(customers.count)
  end

  #  How many scans will need to occur before a certain type of match
  # e.g. Customer.scans_until_match("followers", {followers:50000})  --> 1200

  def self.scans_until_match(match_type, options = { score: 0, followers: 0 })
    score = options[:score]
    num_followers = options[:followers]

    if match_type == 'imdb'
      (100 / percentage_with_imdb_match).ceil
    elsif match_type == 'wikipedia'
      (100 / percentage_with_wikipedia_match).ceil
    elsif match_type == 'klout'
      (100 / percentage_with_klout_score(score)).ceil
    elsif match_type == 'followers'
      (100 / percentage_with_followers(num_followers)).ceil
    end
  end

  protected

  def set_wikipedia
    self.wikipedia_url = @wikipedia.url
    self.wikipedia_bio = @wikipedia.bio
  end

  def set_imdb
    self.imdb_url = @imdb.url
    self.imdb_bio = @imdb.bio
  end

  def set_angellist
    @fullcontact.profile_hash('angellist')
    self.angellist_bio = @fullcontact.profile_data('bio')
    self.angellist_url = @fullcontact.profile_data('url')
  end

  def set_instagram
    instagram = Instagram.new(self)
    self.instagram_id = instagram.id
    self.instagram_followers = instagram.followers
    self.instagram_url = instagram.url
  end

  def set_klout
    @fullcontact.profile_hash('klout')
    self.klout_id = @fullcontact.profile_data('id')
    self.klout_url = @fullcontact.profile_data('url')
    klout = Klout.new(self)
    self.klout_score = klout.score
  end

  def set_linkedin
    @fullcontact.profile_hash('linkedin')
    self.linkedin_bio = @fullcontact.profile_data('bio')
    self.linkedin_url = @fullcontact.profile_data('url')
  end

  def set_twitter
    @fullcontact.profile_hash('twitter')
    self.twitter_followers = @fullcontact.profile_data('followers')
    self.twitter_url = @fullcontact.profile_data('url')
    self.twitter_bio = @fullcontact.profile_data('bio')
  end

  def set_youtube
    @fullcontact.profile_hash('youtube')
    self.youtube_url = @fullcontact.profile_data('url')
    self.youtube_username = @fullcontact.profile_data('username')
    youtube = Youtube.new(self)

    self.youtube_subscribers = youtube.subscribers
    self.youtube_views = youtube.views
  end

  def sanitize
    self.first_name = first_name.sanitize_name if first_name.present?
    self.last_name = last_name.sanitize_name if last_name.present?
    self.email = email.sanitize_email if email.present?
  end

  private

  # sent out to store owner when they use up their last scan
  def scans_depleted_notification
    shop = self.shop
    NotificationMailer.scans_depleted(shop).deliver_now if shop.social_scans_remaining == 1
  end
end

app/controllers/customers_controller.rb
class CustomersController < AuthenticatedController
  skip_before_action :verify_authenticity_token, :only => :bulk_scan
  layout 'true' == Figaro.env.shopify_embedded_app ? 'embedded_app' : 'application'

  def index
    @shop = current_shop
    @customer = current_shop.customers.new
    @celebrities = current_shop.celebrities.page(params[:page]).per(10)
    @plan = current_shop.plan
    @basic_scans_remaining = current_shop.basic_scans_remaining
    @social_scans_remaining = current_shop.social_scans_remaining
    @free_influencer_scans_remaining = current_shop.free_influencer_scans_remaining
    @bulk_scans_allowed = Plan.bulk_scans_allowed?(@plan)

    if @basic_scans_remaining < 1
      flash[:alert] = 'You have no more customer scans remaining. Upgrade your plan in settings.'
    end
  end

  def show
  end

  def destroy
    @celebrity = current_shop.customers.find(params[:id])

    if @celebrity.destroy
      redirect_to customers_path
    else
      flash.now[:alert] = 'There was an error.'
      render :index
    end
  end

  def create
    if current_shop.basic_scans_remaining > 0
      @customer = current_shop.customers.new(customer_params)
      @customer.scan
      @customer.save

      if @customer.celebrity?
        render 'create.js.erb'
      elsif current_shop.social_scans_remaining < 1
        flash.now[:notice] = 'No Wikipedia or IMDB Match.'
        render 'not_a_celebrity.js'
      else
        flash.now[:notice] = "That ain't no celebrity, kid."
        render 'not_a_celebrity.js'
      end

    else
      flash.now[:notice] = 'You have no scans remaining :('
      render 'not_a_celebrity.js'
    end
  end

  def archive
    @customer = current_shop.customers.find(params[:id])
    @customer.archived = true
    if @customer.save
      render nothing: true, status: 200
    else
      render nothing: true, status: 404
      flash[:alert] = 'There was an error with your archive.'
    end
  end

  def unarchive
    @customer = current_shop.customers.find(params[:id])
    @customer.archived = false
    if @customer.save
      redirect_to customers_url
    else
      render :index
    end
  end

  def bulk_scan
    return unless current_shop.basic_scans_remaining > 0 && Plan.bulk_scans_allowed?(current_shop.plan)

    num = bulk_scan_params[:quantity].to_f
    # scan_existing = bulk_scan_params[:include_scanned].present?
    scan_existing = true
    Resque.enqueue(BulkScanner, current_shop.id, num, scan_existing)

    @time = (num / 6).ceil
    @celebrities = current_shop.customers.where(status: "celebrity")

    respond_to do |format|
      format.js do
        ## polling would go here
        flash.now[:success] = "Bulk influencer scan processing."
        render :bulk_scan
      end
      format.html do
        flash[:notice] = "Bulk influencer scan processing. Refresh to see results."
        redirect_to customers_path
      end
    end
  end

  def celebrity_poll
    respond_to do |format|
      format.js do
        render :celebrity_poll
      end
    end
  end

  protected

  def customer_params
    params.require(:customer).permit(
      :first_name, :last_name, :email)
  end

  def bulk_scan_params
    params.permit(
      :include_scanned, :quantity)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def wikipedia_link(customer)
    if customer.wikipedia_url.present?
      link_to 'Yes', customer.wikipedia_url, target: '_blank'
    else
      '—'
    end
  end

  def imdb_link(customer)
    if customer.imdb_url.present?
      link_to 'Yes', customer.imdb_url, target: '_blank'
    else
      '—'
    end
  end

  def twitter_follower_count(customer)
    if !customer.scanned_on_social?
      '—'
    elsif customer.twitter_celebrity? && customer.twitter_url
      link_to customer.twitter_followers, customer.twitter_url, target: '_blank'
    elsif customer.twitter_celebrity?
      customer.twitter_followers
    else
      '—'
    end
  end

  def name(customer)
    if customer.shopify_url.present?
      link_to customer.full_name, 'https://' + customer.shopify_url, target: '_blank'
    else
      customer.full_name
    end
  end

  def bio(customer)
    if customer.twitter_bio
      customer.twitter_bio
    elsif customer.linkedin_bio
      customer.linkedin_bio
    elsif customer.angellist_bio
      customer.angellist_bio
    elsif customer.twitter_bio
      customer.twitter_bio
    elsif customer.wikipedia_bio
      customer.wikipedia_bio
    elsif customer.imdb_bio
      customer.imdb_bio
    else
      'No bio at this time.'
    end
  end

  def klout_score(customer)
    if !customer.scanned_on_social?
      '—'
    elsif customer.klout_celebrity?
      link_to customer.klout_score, 'https://klout.com/corp/score', target: '_blank'
    else
      '—'
    end
  end

  def youtube_subscriber_count(customer)
    if !customer.scanned_on_social?
      '—'
    elsif customer.youtube_celebrity? && customer.youtube_url
      link_to customer.youtube_subscribers, customer.youtube_url, target: '_blank'
    elsif customer.youtube_celebrity?
      subscribers
    else
      '—'
    end
  end

  def instagram_follower_count(customer)
    if !customer.scanned_on_social?
      '—'
    elsif customer.instagram_celebrity? && customer.instagram_url
      link_to customer.instagram_followers, customer.instagram_url, target: '_blank'
    elsif customer.instagram_celebrity?
      customer.instagram_followers
    else
      '—'
    end
  end
end

app/views/customers/_app_explanation.html.erb
<div class="spacer"></div>

<div class="row">
  <div class="text-center col-sm-8 col-sm-offset-2">
    <b>Alpha Club will automatically scan your new orders and notify you when one of your customers is an influencer.</b>
  </div>
</div>

<div class="spacer"></div>

app/views/customers/_bulk_import.html.erb
<div class="spacer"></div>

<%= form_tag bulk_scan_path, :id=>"bulk_scan_form", :remote => true do %>
	<div class="row vertical-align bulk-import">
	  <div class="text-center col-sm-4">
	    <% if @bulk_scans_allowed %>
	    	<%= submit_tag "Find Influencers", :class=>"btn btn-danger", :id => "bulk-scan" %>
	    <% else %>
	    	<div class="tooltip-wrapper">
	    		<div class="tooltip">Upgrade plan to access bulk scanner</div>
	    		<%= submit_tag "Bulk Scan", :class=>"btn btn-danger btn-disabled", :id => "bulk-scan", :disabled=> true %>
	    	</div>
	    <% end %>
	  </div>
	  <div class="col-sm-8">
	     <p>Scan your <%= number_field_tag 'quantity', 50, in: 1..@social_scans_remaining %> most recent customers.</p>
	     <%= hidden_field_tag :include_scanned, '' %>
	    <!--  <%= check_box_tag :include_scanned %> <em>Include customers who have already been scanned by Alpha Club</em> -->
	  </div>
	</div>
<% end %>

<div class="spacer"></div>

app/views/customers/_celebrity_table.html.erb
  <div class="clearfix"></div>
  <div class="spacer"></div>



    <table class="table customers-container table-hover">
     <thead>
      <tr>
        <%= render 'table_headers'  %>
      </tr>
     </thead>

     <tbody>

        <% celebrities.each do |celebrity| %>
          <%= render 'celebrity_table_row', :celebrity=> celebrity %>
       <% end %>
     </tbody>
    </table> 

app/views/customers/_celebrity_table_row.html.erb
<tr class='celebrity-row'>
   <td>
      <%= link_to customer_archive_path(celebrity), :remote=>"true" do %>
        <i class="glyphicon glyphicon-remove"></i>
      <% end %>  
   </td>
   <td><%= name(celebrity) %></td>
   <td><%= bio(celebrity) %></td>


   <% if current_shop.wikipedia_notification %>
     <td><%= wikipedia_link(celebrity) %></td>
   <% end %>

    <% if current_shop.imdb_notification %>
     <td><%= imdb_link(celebrity) %></td>
   <% end %>

   <% if current_shop.plan == "free" || current_shop.plan == "junior" %>
    <td><em>upgrade to enable</em></td>
   <% else %>
     <td><%= klout_score(celebrity) %></td>
     <td><%= youtube_subscriber_count(celebrity) %></td>
     <td><%= twitter_follower_count(celebrity) %></td>
     <td><%= instagram_follower_count(celebrity) %></td>
   <% end %>

   
   
   
   
</tr>

app/views/customers/_header.html.erb
<div class="spacer"></div>

<div style="text-align:left">
	<%= link_to image_tag('logo-light.png', :height=>"50px"), root_url %>
</div>

<div style="text-align:right;">
	<%= render 'shops/scans_remaining' %>


	    <%= link_to edit_shop_path do %>
	    	<i class="glyphicon glyphicon-cog"></i> Settings & Notifications
	   	<% end %>
  </div>

app/views/customers/_index_scanner.html.erb
 
    <div class="text-center scanner">
       
          <%= form_for @customer, :remote=> true do |f| %>

            <div class="row" style="width:90%; margin:0 auto;">
              <div class="form-group col-sm-3">
                <%= f.text_field :first_name, class:"form-control", placeholder: "first name" %>
              </div>

              <div class="form-group col-sm-3">
                <%= f.text_field :last_name, class:"form-control", placeholder: "last name" %>
              </div>

              <div class="form-group col-sm-3">
                <%= f.text_field :email, class:"form-control", placeholder: "email (optional)" %>
              </div>
          
               <div class="form-group col-sm-3">
                 <%= f.submit "Single Scan", class:"btn btn-primary scan" %>
               </div>
            </div>
          <% end %>
      </div>
    

app/views/customers/_scanner.html.erb
 
    <div class="text-center scanner">
       
        <div class="clearfix small-spacer"><br /></div>
          <%= form_for @customer do |f| %>

            <div class="row" style="width:90%; margin:0 auto;">
              <div class="form-group col-sm-4">
                <%= f.label :first_name, "First Name" %>
                <%= f.text_field :first_name, class:"form-control", placeholder: "e.g. jack" %>
              </div>

              <div class="form-group col-sm-4">
                <%= f.label :last_name, "Last Name" %>
                <%= f.text_field :last_name, class:"form-control", placeholder: "e.g. dorsey" %>
              </div>

              <div class="form-group col-sm-4">
                <%= f.label :email, "Email (optional for Twitter count)" %>
                <%= f.text_field :email, class:"form-control" %>
              </div>
            </div>
            <div class="row">
                <div class="small-spacer"></div>
               <div class="form-group col-sm-12">
                 <%= f.submit "Individual Scan", class:"btn btn-primary scan" %>
               </div>
            </div>
          <% end %>
      </div>
    
    

app/views/customers/_scans_remaining.html.erb
<div class="spacer"></div>

<div style="text-align:right;">
	<% if @plan == "free" %>
	 	<h4><span id="scans-remaining"><%= @scans_remaining %></span> free customer scans remaining (<%= link_to "change plan", plan_path %>)</h4>
	<% else %>
	 	<h4><span id="scans-remaining"><%= @scans_remaining %></span> customer scans remaining this month (<%= link_to "change plan", plan_path %>)</h4>
	<% end %>

	    <%= link_to edit_shop_path do %>
	    	<i class="glyphicon glyphicon-cog"></i> Settings & Notifications
	   	<% end %>
  </div>

app/views/customers/_table_headers.html.erb
<th></th>
<th>Customer</th>
<th>Summary</th>

<% if current_shop.wikipedia_notification %>
  <th>Wikipedia</th>
<% end %>

<% if current_shop.imdb_notification %>
  <th>IMDB</th>
<% end %>

<% if current_shop.plan == "free" || current_shop.plan == "junior" %>
  <th>Social Follower Counts</th>
<% else %>
  <th>Klout</th>
  <th>Youtube</th>
  <th>Twitter</th>
  <th>Instagram</th>
<% end %>

app/views/customers/bulk_scan.js.erb
$('.container').prepend("<%= j render(:partial => 'layouts/flash_messages', :locals=> {:time => @time}) %>")

addBlur();
setTimeout(function(){  
  removeBlur();
  $('.celebs').html("<%= j render(:partial => 'customers/celebrity_table', :locals=> {:celebrities => @celebrities}) %>")
}, 1500);

app/views/customers/create.js.erb
removeBlur()

$('tbody').prepend("<%= j render(:partial => 'celebrity_table_row', :locals=> {:celebrity => @customer}) %>")

app/views/customers/index.html.erb
<div class="container">

	<%= render 'header' %>

<!-- 	<%= render 'app_explanation' %>
 -->
	<%= render 'bulk_import' %>

<!-- 	<%= render 'index_scanner' %>
 -->
	<div class="celebs">
	  <%= render 'celebrity_table', celebrities: @celebrities %>
	</div>

</div>

app/views/customers/new.html.erb
<div class="container">

<%= render 'app_explanation' %>

 <h1>No influencers discovered yet :(</h1>
 <h5>Try adding one manually to see how it works:</h5>

<%= render 'scanner' %>

</div>

app/views/customers/not_a_celebrity.js.erb
$('.container').removeClass('blur');
$('.load-ajax').hide()

$('body').prepend("<%= j render 'layouts/flash_messages' %>")