config/routes.rb
Rails.application.routes.draw do
  root to: 'onboarding#index'
  mount ShopifyApp::Engine, at: '/'
  mount Resque::Server, at: '/resque'

  get '/welcome' => 'onboarding#index', as: :welcome
  get '/welcome/scan' => 'onboarding#scan', as: :welcome_scan
  get '/welcome/status' => 'onboarding#status', as: :welcome_status
  get '/welcome/result' => 'onboarding#result', as: :welcome_result

  get '/customer/archive/:id' => 'customers#archive', as: :customer_archive
  get '/customer/unarchive/:id' => 'customers#unarchive', as: :customer_unarchive

  resources :customers, only: [:index, :show, :new, :create, :destroy]
  resource :shop, only: [:edit, :update]
  get '/shop/plan' => 'shops#plan', as: :plan
  get '/shop/plans/update_plan_step_2' => 'shops#update_plan_step_2', as: :update_plan_step_2
  patch '/shop/plans/update_plan_step_1' => 'shops#update_plan_step_1', as: :update_plan_step_1
  post '/customer/bulk_scan' => 'customers#bulk_scan', as: :bulk_scan

  scope '/hooks', controller: :hooks do
    post :new_customer_callback
    post :app_uninstalled_callback
  end

end

app/controllers/onboarding_controller.rb
class OnboardingController < AuthenticatedController
  respond_to :html, :json

  def index
    redirect_to customers_path
     # if current_shop.onboarded  << skipping onboard for mike demo
  end

  def scan
    if !current_shop.onboarded
      Resque.enqueue(Onboard, current_shop.id)
      current_shop.update_attributes onboard_status: 'queued'
    else
      flash[:info] = "You've already used your free scan :("
      render js: "window.location = '#{customers_path}'"
    end
  end

  def status
    @shop = current_shop
    render json: @shop
  end

  def result
    @celebrity = current_shop.celebrities.last
  end
end

app/views/onboarding/_celebrity.html.erb
<div class="text-center">
	<div class="spacer">
		<h1>Boom! We found an influencer:</h1>
		<h5>You should offer this customer a free product in return for a shout out on social.</h5>
	</div>

	<div class="well">

		<h2><%= name(@celebrity) %></h2>

		<p><%= bio(@celebrity) %></p>

		<ul>
		<% if @celebrity.wikipedia_celebrity? %>
		   <li>Wikipedia Page: <%= wikipedia_link(@celebrity) %></li>
		 <% end %>

		  <% if @celebrity.imdb_celebrity? %>
		   <li>IMDB Page: <%= imdb_link(@celebrity) %></li>
		 <% end %>

		 <% if @celebrity.klout_celebrity? %>
		   <li>Klout Score: <%= klout_score(@celebrity) %></li>
		 <% end %>

		  <% if @celebrity.youtube_celebrity? %>
		   <li>Youtube Subscribers: <%= youtube_subscriber_count(@celebrity) %></li>
		 <% end %>

		 <% if @celebrity.twitter_celebrity? %>
		   <li>Twitter Followers: <%= twitter_follower_count(@celebrity) %></li>
		 <% end %>

		 <% if @celebrity.instagram_celebrity? %>
		   <li>Instagram Followers: <%= instagram_follower_count(@celebrity) %></li>
		 <% end %>
		</ul>

	</div>


	<%= link_to plan_path do %>
		<div class="btn btn-info text-center small-spacer" style="padding: 10px 40px;">
			<h4>Upgrade plan for automatic monthly scanning</h4>
		</div>
	<% end %>


	<p><%= link_to "Continue to the app with scans disabled >", customers_path %></p>
</div>

   

app/views/onboarding/_no_celebrity.html.erb
<div class="text-center">
	<h1>Dang, we couldn't find any influencers in our initial scan.</h1>

	<%= link_to customers_path do %>
		<div class="btn btn-info text-center small-spacer" style="padding: 10px 40px;">
			<h4>Continue to the app ></h4>
		</div>
	<% end %>

</div>

<div class="spacer"></div>

app/views/onboarding/index.html.erb
<div class="container">
	<div class="spacer text-center">
		<%= image_tag("logo-red.png") %>
	</div>

	<div class="text-center">
		<h1>Thanks for installing Alpha Club. Let us show you how it works.</h1>

		<%= link_to welcome_scan_path, :id=>"onboard-scanner", :remote => true do %>
			<div class="btn btn-info text-center small-spacer" style="padding: 10px 40px;">
				<h4>Find an influencer in my store</h4>
			</div>
		<% end %>

		<p><%= link_to "No thanks, take me directly to the app >", customers_path %></p>
	</div>

	<div class="status" data-url="<%= welcome_status_path %>">
	</div>
	<div class="result" data-url="<%= welcome_result_path %>">
	</div>

</div>

app/views/onboarding/result.html.erb
<div class="container">

	<div class="spacer text-center">
			<%= image_tag("logo-red.png") %>
	</div>


	<% if @celebrity %>
		<%= render 'celebrity' %>
	<% else %>
		<%= render 'no_celebrity' %>
		<%= render 'shops/celebrity_odds' %>
	<% end %>

	<div class="spacer"></div>

</div>



   

app/views/onboarding/scan.js.erb
// stop polling after ~2 minutes (while count is less  than 50)
var count = 0

var OnboardingPoller;


OnboardingPoller = {
  poll: function() {
    console.log('scanning')
    count += 1
    console.log(count)
    return setTimeout(this.request, 2500);
  },
  request: function() {
    var status_url = $('.status').data('url')
    var result_url = $('.result').data('url')


    $.ajax({
        type: "GET",
        url: status_url,
        dataType: "json",
        success: function(data){
            console.log(data.onboard_status)

            if (data.onboard_status == "queued" && count < 50){
              OnboardingPoller.poll();
            } 
            else {
              window.location = result_url
            }
        }  

    });
    
  }
};

$(function() {
  return OnboardingPoller.poll();
});